### ISSUE TITLE
dependency errors

### ISSUE THREAD

**Issue by teeuwis** [SkyJedi/RPG-Web-Character-Creator#13]
I am getting these dependency errors. Can you advice what to do?

Cheers,
Teeuwis

> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
> npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).

**Comment by SkyJedi** [comment]
Update them? Neither one of those is required for this.

**Comment by teeuwis** [comment]
I am pretty new to node.js, but they are mentioned as dependency in package-lock.json

Should I alter the package-lock.json file? Or just manually upgrade using npm command?

Sorry for the noobie questions ;-)

**Comment by SkyJedi** [comment]
Manually upgrade?  I really don't know.  Package-lock is a  auto generated
thing that I usually just delete

-SkyJedi
https://www.patreon.com/SkyJedi

**Comment by HolmstN** [comment]
You should `npm uninstall` the bad packages and then `npm install` the new packages.  The package-lock should regen.

*Stealth ninja away*

**Comment by SkyJedi** [comment]
God bless you Stealth Ninja!

**Comment by aabenoja** [comment]
@teeuwis You should never edit the `package-lock.json` file directly. When managing packages in a node project you should always use the npm commands to do so.

`package-lock.json` is there to optimize reinstallation by tracking all installed dependencies and caching them. This is especially useful in a continuous integration environment such as travis-ci, where npm can leverage a cache to install dependencies in a consistent directory structure across multiple runs. This feature is only available if you use `npm ci` instead of `npm install.` The later command does not heed the lock file and will grab the latest version of all dependencies and devDependencies based on the provided version constraints in `package.json` and update the lock file as necessary.

Per @SkyJedi's comment, neither `circular-json` nor `kleur` are direct dependencies of this project as specified by `package.json`

**Comment by teeuwis** [comment]
@aabenoja thank you for the feedback and dully noted.

I use the PLESK interface to implement Node JS on my webhosting. It detects the package.json to install any dependencies. I have no clue why my system is giving these errors. I have removed the lock and removed the node_modules folder to start over.

It's still giving the same errors when I use PLESK to handle the installation. So I will resort to command line style I guess. I'll update this thread how this goes so other PLESK users will be helped.

**Comment by aabenoja** [comment]
What you are seeing is normal NPM behavior. The original publishers of the `circular-json` and `kleur` packages have marked their respective modules as deprecated. Whenever npm pulls down a deprecated project it will `WARN` the users that a package is no longer supported and should update.
It should be noted that this isn't an `ERROR` in the fatal sense. (In fact, npm will also display errors in its logging with `npm ERROR`.)

I will stress again, neither of these two packages are ***direct dependencies***. Some version of an indirect dependency, a dependency of one of the dependencies somewhere down this node project's dependency tree, is using a deprecated package is all this error amounts to. Since it's a third-party package that needs to update its deprecated package(s) this is not a concern for this project.

That all being said, I'm not sure if PLESK is giving you an error dialog about the deprecated packages as a blanket catch-all for any errors/warnings. It'd be nice if that tool offers settings to mute deprecation warnings.
