### ISSUE TITLE
Custom Data > `Archetypes` Losing their info when you select Edit to change settings in them.

### ISSUE THREAD

**Issue by dlwest72** [SkyJedi/RPG-Web-Character-Creator#21]
**Describe the bug** Custom Data > `Archetypes` Losing their info when you select Edit to change settings in them.

**To Reproduce** 

1. Go to https://genesysemporium.com/ as dlwest72@gmail.com
2. Click on Custom Data > `Archetypes` select edit for `Intellectual`
3. Remove any setting in my case a custom setting was showing there that shouldn't be showing
4. It cleared out all the Starting `Characteristic Bonuses`, `skills`, etc
5. Seems to happen on several different ones.
6. Expected behavior Should be able to access and modify `Settings` for an `Archetypes` without losing their default setup

**Screenshots**
![archetypes](https://user-images.githubusercontent.com/4602770/52182198-479a2800-27c0-11e9-9910-371634fbd43b.jpg)

**Desktop:**

- OS: HIgh Sierra 10.13.6 
- Browser Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by SkyJedi** [comment]
Hmmmm, this won't be an issues after restructuring is done.

It looks like this is a settings add on for Intellectual?  It can be
deleted as it doesn't add anything anymore

-SkyJedi
https://www.patreon.com/SkyJedi

**Comment by SkyJedi** [comment]
Yeah, your not losing data.  The data in these objects is just the name and setting so there is nothing to fill the rest of the object with so it reverts to defaults.  Since setting has been remove, the user can remove the  objects on the custom data page.

Side Note: Please don't blast me on every point of contact in a span of 45 minutes on a sunday afternoon for what amounts to a cosmetic bug.  Posting once in one spot is enough.  I will see it.
